<?php


/**
 * Skeleton subclass for performing query and update operations on the 'nc_tracker_entry' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jun 27 03:16:29 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.ncTrackerPlugin.lib.model
 */
class ncTrackerEntryPeer extends BasencTrackerEntryPeer
{
  static public function createFromAction(sfAction $action, PropelPDO $con = null)
  {
    $entry = new ncTrackerEntry();

    $entry->fromAction($action);
    $entry->save($con);

    return $entry;
  }

  /**
   * Get all the different values set to $column.
   *
   * @param  string    $column The column from this class' table.
   * @param  PropelPDO $con    Optional PDO object.
   * @return array
   */
  static public function retrieveAllValuesForColumn($column, PropelPDO $con = null)
  {
    $criteria = new Criteria();

    $criteria->setDistinct();
    $criteria->clearSelectColumns();
    $criteria->addSelectColumn($column);

    return ncTrackerEntryPeer::doSelectStmt($criteria)
      ->fetchAll(PDO::FETCH_COLUMN);
  }
} // ncTrackerEntryPeer
